In [ ]:
%load_ext autoreload
%autoreload 2
import warnings
import numpy as np
warnings.simplefilter(action='ignore', category=FutureWarning)
from study_library import *


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [31]:
first_analysis = analysis()

In [ ]:
spectra = first_analysis.uniform_generation(seed_points = [3,8])
minimas = first_analysis.find_min_dataset(spectra[0])
mean_minimas = np.mean(minimas)
var_minimas = np.var(minimas)

In [71]:
minimas = first_analysis.find_min_dataset(spectra[0])
mean_minimas = np.mean(minimas)
var_minimas = np.var(minimas)

In [72]:
print(f"the average minima is {mean_minimas} for a variance of: {var_minimas}")

the average minima is 0.05127057528809178 for a variance of: 0.00019141570789382584


In [3]:
spectra, df1 = first_analysis.weighted_generation(seed_points = [3,8])
minimas = first_analysis.find_min_dataset(spectra)
mean_minimas = np.mean(minimas)
var_minimas = np.var(minimas)

In [40]:
print(f"the average minima is {mean_minimas} for a variance of: {var_minimas}")

the average minima is 0.056546821899727664 for a variance of: 0.00022692162894494578


In [4]:
import numpy as np
np.random.dirichlet(np.ones(7)).sum()

np.float64(1.0)

In [12]:
weights = np.array([0.18125453, 0.0866882, 0.04171468,0.1667358, 0.32207991, 0.06511547, 0.1364114 ])

In [32]:
import pygad
import numpy as np

def fitness_func(ga_instance,solution, solution_idx):
    normalized_weights = np.array(solution)
    normalized_weights = normalized_weights/normalized_weights.sum()

    lol = first_analysis.weighted_generation_parallel(weight = normalized_weights, seed_points = [3,8])
    spectra = np.concatenate(lol)
    minimas = first_analysis.find_min_dataset(spectra)
    mean_minimas = np.mean(minimas)
    var_minimas = np.var(minimas)
    return mean_minimas

def on_start(ga_instance):
    for i in range(ga_instance.sol_per_pop):
        ga_instance.population[i] = np.random.dirichlet(np.ones(ga_instance.num_genes))

def on_generation(ga_instance):
    global last_fitness
    best_solution, best_fitness, _ = ga_instance.best_solution(pop_fitness=ga_instance.last_generation_fitness)
    
    print(f"Generation = {ga_instance.generations_completed}")
    print(f"Fitness    = {best_fitness}")
    print(f"Change     = {best_fitness - last_fitness}")
    print(f"Genes      = {best_solution}")
    
    last_fitness = best_fitness

mutation_percent_genes=30  # or adjust based on num_genes
num_genes=7
ga_instance = pygad.GA(
    num_generations=5,
    num_parents_mating=5,
    fitness_func=fitness_func,
    sol_per_pop=10,
    num_genes=num_genes,
    init_range_low=0.2,
    init_range_high=1,
    on_start=on_start,
    gene_space={'low': 0.2, 'high': 1},
    mutation_percent_genes=mutation_percent_genes,
    on_generation=on_generation,
    keep_elitism=2
)

ga_instance.run()

# Best solution
solution, fitness, _ = ga_instance.best_solution()
print("Best:", solution)
print("Sum:", np.sum(solution))

/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Generation = 1
Fitness    = 0.05927813309247158
Change     = -0.004605238026072628
Genes      = [0.02065873 0.12101462 0.08081627 0.21978619 0.03734141 0.10918676
 0.41119603]


/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Generation = 2
Fitness    = 0.06498920405423846
Change     = 0.005711070961766873
Genes      = [0.02065873 0.12101462 0.08081627 0.11466537 0.30777906 0.44471586
 0.94027366]


/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Generation = 3
Fitness    = 0.06498920405423846
Change     = 0.0
Genes      = [0.02065873 0.12101462 0.08081627 0.11466537 0.30777906 0.44471586
 0.94027366]


/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Generation = 4
Fitness    = 0.06498920405423846
Change     = 0.0
Genes      = [0.02065873 0.12101462 0.08081627 0.11466537 0.30777906 0.44471586
 0.94027366]


/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Generation = 5
Fitness    = 0.0657191357611746
Change     = 0.0007299317069361377
Genes      = [0.02065873 0.12101462 0.08081627 0.20345065 0.37738606 0.90268619
 0.68904768]


/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:186: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Best: [0.02065873 0.12101462 0.08081627 0.20345065 0.37738606 0.90268619
 0.68904768]
Sum: 2.3950601820632214


## Genetic selection with database

##### let'ts take inspiration from the best weights we got from our genettic category weight selection to maximize difference

In [74]:
weights = np.array([0.02065873,0.12101462,0.08081627,0.11466537,0.30777906,0.44471586])

normalized_weights = np.array(weights)
normalized_weights = normalized_weights/normalized_weights.sum()

lol = first_analysis.weighted_generation_parallel(number_of_samples=40000, weight = normalized_weights, seed_points = [3,9])

/Users/billpro/shapes_adapted/study_library.py:185: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:185: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
/Users/billpro/shapes_adapted/study_library.py:185: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

In [75]:
final_spectra  = np.concatenate(lol)


In [ ]:
final_spectra = final_spectra[np.random.permutation(final_spectra.shape[0]), :]

In [83]:
import pygad
import numpy as np

rarg_spectra = final_spectra.reshape(1000,40,-1)
def fitness_func(ga_instance,solution, solution_idx):
    global rarg_spectra
    axis_0 = np.arange(0,1000)
    axis_1 = solution

    selection = rarg_spectra[axis_0,axis_1,:]
    minimas = first_analysis.find_min_dataset(selection)
    mean_minimas = np.mean(minimas)
    var_minimas = np.var(minimas)
    return mean_minimas



def on_generation(ga_instance):
    best_solution, best_fitness, _ = ga_instance.best_solution(pop_fitness=ga_instance.last_generation_fitness)
    
    print(f"Generation = {ga_instance.generations_completed}")
    print(f"Fitness    = {best_fitness}")
    print(f"Genes      = {best_solution}")
    

mutation_percent_genes = 50  # starting value
num_genes = 1000
gene_space_array = np.arange(0, 40, dtype=int)

ga_instance = pygad.GA(
    num_generations=100,
    num_parents_mating=20,
    fitness_func=fitness_func,
    sol_per_pop=100,
    num_genes=num_genes,
    gene_space=gene_space_array,
    mutation_percent_genes=mutation_percent_genes,  # initial value
    on_generation=on_generation,
    keep_elitism=2,
    gene_type=int,
    parent_selection_type="tournament",
    K_tournament=3
)


ga_instance.run()

# Best solution
solution, fitness, _ = ga_instance.best_solution()
print("Best:", solution)
print("Sum:", np.sum(solution))

Generation = 1
Fitness    = 0.060117898567250104
Genes      = [26  5 23  4 10 17 22 24  0 33 34  3 29  6 23  5 16  0 36 14 37 25  0  7
 22 33 12 15 28 36 36  1 30  4 13 26 17  5 23 26 11  4  1 34 36 35 26  6
 32 15  6 18 18  8 27 32 28 34 13 16 12 16  4 17  5  8 30  8 14 15  6 16
 39 32 30  3 21 23 16 22  4 10 38 35  4 20 22  2 23 17 33  0  4 21 17 39
 38 16 22 20  3 34 12 34  2 10 16 28 32  8  8 32  7  2 10 26 36  7 10  2
  2  5 24  6 28 33 31 16 27 17 29 11 16 38 10 26 39  7 21  8 31 27 16 35
 26 25 24 33 12 10 32 25 29 19 28 11  5 29 28  1  5 32 36 32 14 36 23 32
 37 23 13  4 21 17 39 18 25  7  5  1 17 25 26 26 11 29  2  8  8 39 25 22
 11 13 28 39 33  1 37  3 20  3 30  5 25  8 26 24 14 16  5 38 32  1 36  6
  6 32 10 30 33 38 31 39 30 36 35 36 33 20 28 24  4 31 15 37  3  2 26 27
  0 16 38 28 36 22 28 25 24 13 33 31 29 13 29 32 21 10 34 14 28  1 32 20
 31 37 20  7 38 17 15 18 17 33 11 29  0  4 19 38 15  2 27  5 33 36  9  7
 38 36 27  8  0 38 16  2 36 39  5 22 18 11  2  3  1 32 37 39 1

In [35]:
gene_space_array = np.arange(0,200,dtype=int)

In [36]:
gene_space_array.shape

(200,)

In [49]:
import numpy as np

numbers = np.random.randint(0, 20, size=1000)
print(numbers)


[ 9  4 12 10  7  0 17  3 12  7  1 17 10  0  0  2  8 19  7  4 19  9  3 14
  2 13 15  4  2  0 11 10  6  2  0  2 17 17  4  3  1 11 11 13  9  0  8  5
  1  9 11 12  6 13  4 10 12  6  4 17  1 14  2  4  4  2  5  3 11  2 12 12
  8  5 13 19  1 13 11  2  9  2  2 17  3  6 16 11 10  0  2 17 18  8 14 12
 18 12 13  8 11 16 18 18 14  7  9  0  7 18  2 14 10  8 16  8 18  6  7 15
  4 15  3 18 12 10  2  4 13  9 15  8  5 13 16  7 15 18  7 10 19 17  0  6
 11  7 10  6 15 17 13  0  7 18 12 18  2  8  5 18 17  0  6 15  7  0 17  8
  0  5 10  2 12 12  6 15 12  8 17 17  2  4 14 14 17  7 15 13 18 17 12  8
  3  0  9  4  3  1 17  3  2  0  0 10 19  6  2  1  3 15  0 15  2  9  0 15
 14 19 15 15 10 11 19  5  9  4 18  4 11 14 12 19  1  6 17 13  0  1  5  5
 13  4  6  0 14 17 13  7  1  5  5  9 15 11  7  1 18 11 13  5 17 17 10 15
  9 17 13  8 13 12 19 13 17  9  2  3 14  0 16  4 19  4  7  5  6  8 15  9
 15  9 11 15 11  4  0 10  7 10  1 15 15  1  6 11 15  0  7 13 17  9  1 19
 19 13 17 10 15  6  9 17  0  5 12 15  5 12 18 18  3

In [58]:
rarg_spectra = final_spectra.reshape(1000,20,-1)

In [47]:
final_spectra[0,:]

array([ 3.55385551e-01-0.00000000e+00j,  3.50628726e-02-4.25944026e-04j,
        8.42417460e-02+4.44554062e-02j, -1.87915762e-03-5.51696474e-03j,
       -4.23513550e-03+1.35218179e-02j,  1.01423278e-02-2.24764520e-03j,
       -1.09347090e-04-5.78937074e-05j,  2.60072499e-03+3.82091765e-03j,
        7.41062289e-04-2.37873068e-03j,  6.70667283e-04+1.66088748e-03j,
        2.26242510e-03+3.57259103e-05j, -8.34151944e-04-2.98354950e-04j,
        1.57866443e-03+8.38679191e-04j,  5.19889663e-04-7.08040992e-04j,
       -9.54746035e-05+7.89505056e-04j,  1.27405707e-03-3.65134825e-04j,
       -2.69576451e-04+2.90586940e-05j,  7.59132122e-04+4.90540835e-04j,
        3.20392498e-04-6.56769080e-04j,  1.10735201e-04+6.46052955e-04j])

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

row_indices = [0]
rows = np.take(arr, row_indices, axis=1)
print(rows)

[[10 30]
 [40 60]
 [70 90]]


In [52]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

indices = np.arange(arr.shape[0])
values = arr[indices, indices]
print(values)  # [10 50 90]

[10 50 90]


In [53]:
indices

array([0, 1, 2])

In [60]:
axis_0 = np.arange(0,1000)
axis_1 = numbers

selection = rarg_spectra[axis_0,axis_1,:]

In [57]:
rarg_spectra

array([ 3.55385551e-01-0.00000000e+00j,  3.50628726e-02-4.25944026e-04j,
        8.42417460e-02+4.44554062e-02j, -1.87915762e-03-5.51696474e-03j,
       -4.23513550e-03+1.35218179e-02j,  1.01423278e-02-2.24764520e-03j,
       -1.09347090e-04-5.78937074e-05j,  2.60072499e-03+3.82091765e-03j,
        7.41062289e-04-2.37873068e-03j,  6.70667283e-04+1.66088748e-03j,
        2.26242510e-03+3.57259103e-05j, -8.34151944e-04-2.98354950e-04j,
        1.57866443e-03+8.38679191e-04j,  5.19889663e-04-7.08040992e-04j,
       -9.54746035e-05+7.89505056e-04j,  1.27405707e-03-3.65134825e-04j,
       -2.69576451e-04+2.90586940e-05j,  7.59132122e-04+4.90540835e-04j,
        3.20392498e-04-6.56769080e-04j,  1.10735201e-04+6.46052955e-04j])

In [62]:
selection.shape

(1000, 20)